##############################################################################
# Application Settings
##############################################################################

PROJ_NAME     		:= tsys02d_test
SUPPORTED_TARGETS 	:= ceresat

##############################################################################
# Directories
##############################################################################

# Setup Root Directories

APP_ROOT  			:= $(realpath .)
REPO_ROOT 			:= $(realpath $(APP_ROOT)/../..)
CORE_CSIRO_DIR 		:= $(REPO_ROOT)/core_csiro

APPLICATION_SRCS 	:= $(CORE_CSIRO_DIR)/peripherals/sensors/src/tsys02d.c

##############################################################################
# Main Build Rules
##############################################################################

include $(CORE_CSIRO_DIR)/m_common.mk
