/*
 * Copyright (c) 2018, Commonwealth Scientific and Industrial Research
 * Organisation (CSIRO)
 * All rights reserved.
 */

/**
 *      THIS FILE WAS AUTOGENERATED ON {{date}} from gatt.xml.
 * 
 *      THE PURPOSE OF THIS FILE IS SOLELY TO INTIALISE THE GATT TABLE. 
 **/

/* Includes -------------------------------------------------*/

#include "ble.h"

#include "bluetooth_gatt.h"

#include "log.h"

/* Private Defines ------------------------------------------*/
// clang-format off

// clang-format on

/* Type Definitions -----------------------------------------*/

/* Function Declarations ------------------------------------*/

{% for service in gatt_dict['gatt']['service'] %}
{%- if '@id' in service -%}
static eModuleError_t service_{{service['@id']}}( void );
{% for characteristic in service['characteristic'] -%}
{%- if '@id' in characteristic -%}
static eModuleError_t characteristic_{{characteristic['@id']}}( uint16_t usServiceHandle );
{% endif %}
{% endfor -%}

{%- endif %}
{% endfor %}

/* Attribute Handles ----------------------------------------*/

{% for service in gatt_dict['gatt']['service'] -%}
{%- if '@id' in service %}
uint16_t gattdb_{{service['@id']}};
{% for characteristic in service['characteristic'] %}
{% if '@id' in characteristic -%}
uint16_t gattdb_{{characteristic['@id']}};
{% endif -%}
{%- endfor %}
{%- endif -%}
{%- endfor %}

uint16_t *ppusGattProfileHandles[] = {
{{gatt_dict['gatt']|profile_declaration}}
};

/* Private Variables ----------------------------------------*/

/*-----------------------------------------------------------*/

eModuleError_t eGattInit( void )
{
	{% for service in gatt_dict['gatt']['service'] -%}
	{%- if '@id' in service -%}
    service_{{service['@id']}}();
	{% endif -%}
    {%- endfor %}
	return ERROR_NONE;
}

/*-----------------------------------------------------------*/

{% for service in gatt_dict['gatt']['service'] -%}
{%- if '@id' in service -%}
static eModuleError_t service_{{service['@id']}}( void )
{
	{%- if (service['@uuid']|length != 4) %}

	ble_uuid_t			xServiceUUID = { .uuid = 0x{{service['@uuid'][4:8]}}, .type = BLE_UUID_TYPE_UNKNOWN };
	const ble_uuid128_t	xBaseUUID	= { .uuid128={ {{service['@uuid'] | parse_long_uuid}} } };
	uint32_t			ulErrCode;

	/* Add our service to the softdevice */
	ulErrCode = sd_ble_uuid_vs_add( &xBaseUUID, &xServiceUUID.type );
	eLog( LOG_BLUETOOTH_GATT, LOG_VERBOSE, "VS_ADD: %d\r\n", ulErrCode );

	{%- else %}

	ble_uuid_t xServiceUUID = { .uuid = 0x{{service['@uuid']}}, .type = BLE_UUID_TYPE_BLE };
	uint32_t   ulErrCode;
	{% endif %}

	ulErrCode = sd_ble_gatts_service_add( BLE_GATTS_SRVC_TYPE_PRIMARY, &xServiceUUID, &gattdb_{{service['@id']}} );
	eLog( LOG_BLUETOOTH_GATT, LOG_VERBOSE, "SERVICE_ADD: Handle=%d %d\r\n", gattdb_{{service['@id']}}, ulErrCode );

    {% for characteristic in service['characteristic'] -%}
	{%- if '@id' in characteristic %}
    characteristic_{{characteristic['@id']}}( gattdb_{{service['@id']}} );
	{% endif -%}
    {%- endfor %}

    return ERROR_NONE;
}

/*-----------------------------------------------------------*/

{% for characteristic in service['characteristic'] -%}
{%- if '@id' in characteristic -%}
static eModuleError_t characteristic_{{characteristic['@id']}}( uint16_t usServiceHandle )
{
	{%- if characteristic['@uuid']|length != 4 %}

	ble_uuid_t					xCharUUID = { .uuid = 0x{{characteristic['@uuid'][4:8]}}, .type = BLE_UUID_TYPE_UNKNOWN };
	const ble_uuid128_t			xBaseUUID = { .uuid128={ {{characteristic['@uuid'] | parse_long_uuid}} } };
	ble_gatts_char_handles_t	xCharHandles;
	uint32_t					ulErrCode;

	/* Add our command characteristic to the softdevice */
	ulErrCode = sd_ble_uuid_vs_add( &xBaseUUID, &xCharUUID.type );
	eLog( LOG_BLUETOOTH_GATT, LOG_VERBOSE, "VS_ADD: %d\r\n", ulErrCode );

	{%- else %}

	ble_uuid_t				 xCharUUID = { .uuid = 0x{{characteristic['@uuid']}}, .type = BLE_UUID_TYPE_BLE };
	ble_gatts_char_handles_t xCharHandles;
	uint32_t				 ulErrCode;
	{% endif %}

	/* Client Characteristic Configuration Description */
	ble_gatts_attr_md_t xCharMetadataCCCD;
	pvMemset( &xCharMetadataCCCD, 0x00, sizeof( ble_gatts_attr_md_t ) );
	xCharMetadataCCCD.vloc = BLE_GATTS_VLOC_STACK;
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataCCCD.read_perm );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataCCCD.write_perm );

	/* Characteristic Description */
	ble_gatts_char_md_t xCharacteristicSettings;
	pvMemset( &xCharacteristicSettings, 0x00, sizeof( ble_gatts_char_md_t ) );

	{{characteristic|filter_characteristic_properties}}
	xCharacteristicSettings.p_char_user_desc		 = NULL;
	xCharacteristicSettings.p_char_pf				 = NULL;
	xCharacteristicSettings.p_user_desc_md			 = NULL;
	xCharacteristicSettings.p_cccd_md				 = &xCharMetadataCCCD;
	xCharacteristicSettings.p_sccd_md				 = NULL;

	/* Characteristic Value Metadata */
	ble_gatts_attr_md_t xCharMetadataAttr;
	pvMemset( &xCharMetadataAttr, 0x00, sizeof( ble_gatts_attr_md_t ) );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataAttr.read_perm );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataAttr.write_perm );

	xCharMetadataAttr.vloc	= BLE_GATTS_VLOC_STACK;
	xCharMetadataAttr.rd_auth = 0;
	xCharMetadataAttr.wr_auth = 0;
	{{characteristic|filter_characteristic_vlen}}

	/* Characteristic Value */
	ble_gatts_attr_t xCharValue;

	pvMemset( &xCharValue, 0, sizeof( ble_gatts_attr_t ) );

	xCharValue.p_uuid	= &xCharUUID;
	xCharValue.p_attr_md = &xCharMetadataAttr;
	xCharValue.init_len  = 0;
	xCharValue.init_offs = 0;
	{{characteristic|filter_characteristic_value}}
	
	ulErrCode = sd_ble_gatts_characteristic_add( usServiceHandle,
												 &xCharacteristicSettings,
												 &xCharValue,
												 &xCharHandles );
	eLog( LOG_BLUETOOTH_GATT, LOG_VERBOSE, "CHAR_ADD: Handle=%d %d\r\n", xCharHandles.value_handle, ulErrCode );
	gattdb_{{characteristic['@id']}} = xCharHandles.value_handle;
	return ( ulErrCode == NRF_SUCCESS ) ? ERROR_NONE : ERROR_INITIALISATION_FAILURE;
}

/*-----------------------------------------------------------*/

{% endif -%}
{%- endfor -%}
{%- endif -%}
{%- endfor %}