/*
 * Copyright (c) 2020, Commonwealth Scientific and Industrial Research
 * Organisation (CSIRO) ABN 41 687 119 230.
 * All rights reserved.
 *
 * Filename: tdf_auto.h
 *
 * Autogenerated by tdftool
 * 
 * DO NOT EDIT
 */

#ifndef __CORE_CSIRO_LIBRARIES_TDF_AUTO
#define __CORE_CSIRO_LIBRARIES_TDF_AUTO
// clang-format off

/* Includes -------------------------------------------------*/

#include "stdint.h"

#include "tdf_struct.h"

/* Type Definitions -----------------------------------------*/

typedef enum eTdfIds {
{% for SID in tdf_dict|sort %}
    TDF_{{ "%-35s" | format(tdf_dict[SID]['sensor'],)  }} = {{ SID }},
{% endfor %}
} eTdfIds_t;

/* External Variables ---------------------------------------*/

extern const uint8_t pucTdfStructLengths[{{ (tdf_dict | max) + 1 }}];

// clang-format on
#endif /* __CORE_CSIRO_LIBRARIES_TDF_AUTO */
