/*
 * Copyright (c) 2020, Commonwealth Scientific and Industrial Research
 * Organisation (CSIRO) ABN 41 687 119 230.
 * All rights reserved.
 *
 * Filename: tdf_struct.h
 *
 * Autogenerated by tdftool
 * 
 * DO NOT EDIT
 */

#ifndef __CORE_CSIRO_LIBRARIES_TDF_STRUCT
#define __CORE_CSIRO_LIBRARIES_TDF_STRUCT

/* Includes -------------------------------------------------*/

#include "compiler_intrinsics.h"

/* Module Defines -------------------------------------------*/

/* Type Definitions -----------------------------------------*/
// clang-format off

{% for SID in tdf_dict|sort %}
{% if tdf_dict[SID]['info'] != "" %}// {{ tdf_dict[SID]['info'] }}{{ "\n" }}{% endif %}
typedef struct tdf_{{ tdf_dict[SID]['sensor'] | lower }} {
{% for phenom in tdf_dict[SID]['phenomena'] %}
    {{ phenom['type'] }} {{ phenom['phenomenon'] }}{{ phenom['array'] }}; {% if phenom['info'] != "" %}// {{ phenom['info'] }}{% endif %}{{ ' ' }}
{% endfor %}
} ATTR_PACKED tdf_{{ tdf_dict[SID]['sensor'] | lower }}_t;
#define TDF_{{ tdf_dict[SID]['sensor'] }}_SIZE sizeof(tdf_{{ tdf_dict[SID]['sensor'] | lower }}_t)

{% endfor %}

// clang-format on
/* Function Declarations ------------------------------------*/

#endif /* __CORE_CSIRO_LIBRARIES_TDF_STRUCT */
