/*
 * Copyright (c) 2020, Commonwealth Scientific and Industrial Research
 * Organisation (CSIRO) ABN 41 687 119 230.
 * All rights reserved.
 * 
 * Auto generated by tdftool
 * 
 *  DO NOT EDIT
 */

/* Includes -------------------------------------------------*/

#include "tdf_auto.h"

/* Private Defines ------------------------------------------*/
/* Type Definitions -----------------------------------------*/
/* Function Declarations ------------------------------------*/
/* External Variables ---------------------------------------*/
// clang-format off

const uint8_t pucTdfStructLengths[{{ (tdf_dict | max) + 1 }}] = {
{% for SID in tdf_dict|sort %}
    [TDF_{{ "%-35s" | format(tdf_dict[SID]['sensor'],)  }}] = {{ tdf_dict[SID]['bytes'] }},
{% endfor %}
};

// clang-format on
/*-----------------------------------------------------------*/
