/*
 * Copyright (c) 2020, Commonwealth Scientific and Industrial Research 
 * Organisation (CSIRO) ABN 41 687 119 230.
 *
 * Filename: bluetooth_gatt_arch.h
 * Creation_Date: 05/06/2019
 * Author: Jordan Yates <jordan.yates@data61.csiro.au>
 *
 * Redirection to the correct autogenerated gatt header for this architecture 
 * 
 */
#ifndef __CSIRO_CORE_BLUETOOTH_GATT_ARCH
#define __CSIRO_CORE_BLUETOOTH_GATT_ARCH
/* Includes -------------------------------------------------*/

#include "gatt_nrf52.h"

/* Module Defines -------------------------------------------*/

// clang-format off
// clang-format on

/* Type Definitions -----------------------------------------*/

/* Function Declarations ------------------------------------*/
#endif /* __CSIRO_CORE_BLUETOOTH_GATT_ARCH */
